const routesDB = {
  // ============================================================
  // DELTA AIR LINES (DAL)
  // Major hubs: ATL, JFK, LAX, MSP, DTW, SLC, SEA, BOS
  // ============================================================

  // Delta flagship / low-number routes
  'DAL1': { origin: 'JFK', dest: 'LAX' },
  'DAL2': { origin: 'LAX', dest: 'JFK' },
  'DAL3': { origin: 'JFK', dest: 'SFO' },
  'DAL4': { origin: 'SFO', dest: 'JFK' },
  'DAL5': { origin: 'JFK', dest: 'LAX' },
  'DAL6': { origin: 'LAX', dest: 'JFK' },
  'DAL7': { origin: 'JFK', dest: 'SFO' },
  'DAL8': { origin: 'SFO', dest: 'JFK' },
  'DAL9': { origin: 'JFK', dest: 'LAX' },
  'DAL10': { origin: 'LAX', dest: 'JFK' },

  // Delta ATL hub departures
  'DAL401': { origin: 'ATL', dest: 'LAX' },
  'DAL403': { origin: 'ATL', dest: 'LAX' },
  'DAL405': { origin: 'ATL', dest: 'LAX' },
  'DAL421': { origin: 'ATL', dest: 'SFO' },
  'DAL423': { origin: 'ATL', dest: 'SFO' },
  'DAL431': { origin: 'ATL', dest: 'SEA' },
  'DAL433': { origin: 'ATL', dest: 'SEA' },
  'DAL441': { origin: 'ATL', dest: 'JFK' },
  'DAL443': { origin: 'ATL', dest: 'JFK' },
  'DAL445': { origin: 'ATL', dest: 'JFK' },
  'DAL451': { origin: 'ATL', dest: 'BOS' },
  'DAL453': { origin: 'ATL', dest: 'BOS' },
  'DAL455': { origin: 'ATL', dest: 'BOS' },
  'DAL461': { origin: 'ATL', dest: 'ORD' },
  'DAL463': { origin: 'ATL', dest: 'ORD' },
  'DAL471': { origin: 'ATL', dest: 'DFW' },
  'DAL473': { origin: 'ATL', dest: 'DFW' },
  'DAL481': { origin: 'ATL', dest: 'DEN' },
  'DAL483': { origin: 'ATL', dest: 'DEN' },
  'DAL491': { origin: 'ATL', dest: 'MIA' },
  'DAL493': { origin: 'ATL', dest: 'MIA' },
  'DAL501': { origin: 'ATL', dest: 'MSP' },
  'DAL503': { origin: 'ATL', dest: 'MSP' },
  'DAL505': { origin: 'ATL', dest: 'MSP' },
  'DAL511': { origin: 'ATL', dest: 'DTW' },
  'DAL513': { origin: 'ATL', dest: 'DTW' },
  'DAL515': { origin: 'ATL', dest: 'DTW' },
  'DAL521': { origin: 'ATL', dest: 'EWR' },
  'DAL523': { origin: 'ATL', dest: 'EWR' },
  'DAL531': { origin: 'ATL', dest: 'PHX' },
  'DAL533': { origin: 'ATL', dest: 'PHX' },
  'DAL541': { origin: 'ATL', dest: 'LAS' },
  'DAL543': { origin: 'ATL', dest: 'LAS' },
  'DAL551': { origin: 'ATL', dest: 'MCO' },
  'DAL553': { origin: 'ATL', dest: 'MCO' },
  'DAL555': { origin: 'ATL', dest: 'MCO' },
  'DAL561': { origin: 'ATL', dest: 'MSY' },
  'DAL563': { origin: 'ATL', dest: 'MSY' },
  'DAL571': { origin: 'ATL', dest: 'AUS' },
  'DAL573': { origin: 'ATL', dest: 'AUS' },
  'DAL581': { origin: 'ATL', dest: 'BNA' },
  'DAL583': { origin: 'ATL', dest: 'BNA' },
  'DAL591': { origin: 'ATL', dest: 'IAH' },
  'DAL593': { origin: 'ATL', dest: 'IAH' },
  'DAL601': { origin: 'ATL', dest: 'CLT' },
  'DAL603': { origin: 'ATL', dest: 'CLT' },
  'DAL611': { origin: 'ATL', dest: 'SAN' },
  'DAL613': { origin: 'ATL', dest: 'SAN' },
  'DAL843': { origin: 'ATL', dest: 'SAN' },
  'DAL621': { origin: 'ATL', dest: 'BHM' },
  'DAL623': { origin: 'ATL', dest: 'ABQ' },

  // Delta MSP hub
  'DAL711': { origin: 'MSP', dest: 'ATL' },
  'DAL713': { origin: 'MSP', dest: 'ATL' },
  'DAL715': { origin: 'MSP', dest: 'ATL' },
  'DAL721': { origin: 'MSP', dest: 'LAX' },
  'DAL723': { origin: 'MSP', dest: 'LAX' },
  'DAL725': { origin: 'MSP', dest: 'SFO' },
  'DAL727': { origin: 'MSP', dest: 'SEA' },
  'DAL729': { origin: 'MSP', dest: 'JFK' },
  'DAL731': { origin: 'MSP', dest: 'BOS' },
  'DAL733': { origin: 'MSP', dest: 'ORD' },
  'DAL735': { origin: 'MSP', dest: 'DEN' },
  'DAL737': { origin: 'MSP', dest: 'DFW' },
  'DAL739': { origin: 'MSP', dest: 'PHX' },
  'DAL741': { origin: 'MSP', dest: 'LAS' },
  'DAL743': { origin: 'MSP', dest: 'MCO' },
  'DAL745': { origin: 'MSP', dest: 'MIA' },
  'DAL747': { origin: 'MSP', dest: 'EWR' },
  'DAL749': { origin: 'MSP', dest: 'DTW' },
  'DAL751': { origin: 'MSP', dest: 'SAN' },
  'DAL753': { origin: 'MSP', dest: 'AUS' },
  'DAL755': { origin: 'MSP', dest: 'BNA' },
  'DAL757': { origin: 'MSP', dest: 'MSY' },

  // Delta DTW hub
  'DAL801': { origin: 'DTW', dest: 'ATL' },
  'DAL803': { origin: 'DTW', dest: 'ATL' },
  'DAL805': { origin: 'DTW', dest: 'LAX' },
  'DAL807': { origin: 'DTW', dest: 'SFO' },
  'DAL809': { origin: 'DTW', dest: 'SEA' },
  'DAL811': { origin: 'DTW', dest: 'JFK' },
  'DAL813': { origin: 'DTW', dest: 'BOS' },
  'DAL815': { origin: 'DTW', dest: 'ORD' },
  'DAL817': { origin: 'DTW', dest: 'DEN' },
  'DAL819': { origin: 'DTW', dest: 'DFW' },
  'DAL821': { origin: 'DTW', dest: 'PHX' },
  'DAL823': { origin: 'DTW', dest: 'LAS' },
  'DAL825': { origin: 'DTW', dest: 'MCO' },
  'DAL827': { origin: 'DTW', dest: 'MIA' },
  'DAL829': { origin: 'DTW', dest: 'MSP' },
  'DAL831': { origin: 'DTW', dest: 'EWR' },
  'DAL833': { origin: 'DTW', dest: 'CLT' },

  // Delta SLC hub
  'DAL851': { origin: 'SLC', dest: 'ATL' },
  'DAL853': { origin: 'SLC', dest: 'LAX' },
  'DAL855': { origin: 'SLC', dest: 'SFO' },
  'DAL857': { origin: 'SLC', dest: 'SEA' },
  'DAL859': { origin: 'SLC', dest: 'JFK' },
  'DAL861': { origin: 'SLC', dest: 'DEN' },
  'DAL863': { origin: 'SLC', dest: 'PHX' },
  'DAL865': { origin: 'SLC', dest: 'LAS' },
  'DAL867': { origin: 'SLC', dest: 'DFW' },
  'DAL869': { origin: 'SLC', dest: 'MSP' },

  // Delta SEA focus city
  'DAL891': { origin: 'SEA', dest: 'ATL' },
  'DAL893': { origin: 'SEA', dest: 'LAX' },
  'DAL895': { origin: 'SEA', dest: 'SFO' },
  'DAL897': { origin: 'SEA', dest: 'JFK' },
  'DAL899': { origin: 'SEA', dest: 'MSP' },

  // Delta JFK routes
  'DAL411': { origin: 'JFK', dest: 'ATL' },
  'DAL413': { origin: 'JFK', dest: 'ATL' },
  'DAL415': { origin: 'JFK', dest: 'MIA' },
  'DAL417': { origin: 'JFK', dest: 'MCO' },
  'DAL419': { origin: 'JFK', dest: 'BOS' },
  'DAL425': { origin: 'JFK', dest: 'SEA' },
  'DAL427': { origin: 'JFK', dest: 'DEN' },
  'DAL429': { origin: 'JFK', dest: 'MSY' },
  'DAL435': { origin: 'JFK', dest: 'AUS' },
  'DAL437': { origin: 'JFK', dest: 'SAN' },

  // Delta BOS
  'DAL911': { origin: 'BOS', dest: 'ATL' },
  'DAL913': { origin: 'BOS', dest: 'ATL' },
  'DAL915': { origin: 'BOS', dest: 'JFK' },
  'DAL917': { origin: 'BOS', dest: 'DTW' },
  'DAL919': { origin: 'BOS', dest: 'MSP' },

  // ============================================================
  // AMERICAN AIRLINES (AAL)
  // Major hubs: DFW, CLT, MIA, PHX, ORD, JFK, LAX
  // ============================================================

  // American flagship / low-number routes
  'AAL1': { origin: 'JFK', dest: 'LAX' },
  'AAL2': { origin: 'LAX', dest: 'JFK' },
  'AAL3': { origin: 'JFK', dest: 'LAX' },
  'AAL4': { origin: 'LAX', dest: 'JFK' },
  'AAL5': { origin: 'JFK', dest: 'SFO' },
  'AAL6': { origin: 'SFO', dest: 'JFK' },
  'AAL7': { origin: 'JFK', dest: 'SFO' },
  'AAL8': { origin: 'SFO', dest: 'JFK' },

  // American DFW hub departures
  'AAL301': { origin: 'DFW', dest: 'LAX' },
  'AAL303': { origin: 'DFW', dest: 'LAX' },
  'AAL305': { origin: 'DFW', dest: 'LAX' },
  'AAL311': { origin: 'DFW', dest: 'SFO' },
  'AAL313': { origin: 'DFW', dest: 'SFO' },
  'AAL321': { origin: 'DFW', dest: 'JFK' },
  'AAL323': { origin: 'DFW', dest: 'JFK' },
  'AAL325': { origin: 'DFW', dest: 'JFK' },
  'AAL331': { origin: 'DFW', dest: 'ORD' },
  'AAL333': { origin: 'DFW', dest: 'ORD' },
  'AAL335': { origin: 'DFW', dest: 'ORD' },
  'AAL341': { origin: 'DFW', dest: 'MIA' },
  'AAL343': { origin: 'DFW', dest: 'MIA' },
  'AAL345': { origin: 'DFW', dest: 'MIA' },
  'AAL351': { origin: 'DFW', dest: 'ATL' },
  'AAL353': { origin: 'DFW', dest: 'ATL' },
  'AAL361': { origin: 'DFW', dest: 'SEA' },
  'AAL363': { origin: 'DFW', dest: 'SEA' },
  'AAL371': { origin: 'DFW', dest: 'DEN' },
  'AAL373': { origin: 'DFW', dest: 'DEN' },
  'AAL381': { origin: 'DFW', dest: 'PHX' },
  'AAL383': { origin: 'DFW', dest: 'PHX' },
  'AAL391': { origin: 'DFW', dest: 'BOS' },
  'AAL393': { origin: 'DFW', dest: 'BOS' },
  'AAL395': { origin: 'DFW', dest: 'EWR' },
  'AAL397': { origin: 'DFW', dest: 'EWR' },
  'AAL399': { origin: 'DFW', dest: 'CLT' },
  'AAL407': { origin: 'DFW', dest: 'MSP' },
  'AAL409': { origin: 'DFW', dest: 'DTW' },
  'AAL411': { origin: 'DFW', dest: 'LAS' },
  'AAL413': { origin: 'DFW', dest: 'LAS' },
  'AAL415': { origin: 'DFW', dest: 'MCO' },
  'AAL417': { origin: 'DFW', dest: 'MCO' },
  'AAL419': { origin: 'DFW', dest: 'MSY' },
  'AAL421': { origin: 'DFW', dest: 'AUS' },
  'AAL423': { origin: 'DFW', dest: 'AUS' },
  'AAL425': { origin: 'DFW', dest: 'BNA' },
  'AAL427': { origin: 'DFW', dest: 'SAN' },
  'AAL429': { origin: 'DFW', dest: 'IAH' },
  'AAL431': { origin: 'DFW', dest: 'ABQ' },
  'AAL433': { origin: 'DFW', dest: 'ELP' },
  'AAL435': { origin: 'DFW', dest: 'TUS' },
  'AAL437': { origin: 'DFW', dest: 'BHM' },
  'AAL439': { origin: 'DFW', dest: 'JAN' },

  // American CLT hub
  'AAL501': { origin: 'CLT', dest: 'LAX' },
  'AAL503': { origin: 'CLT', dest: 'SFO' },
  'AAL505': { origin: 'CLT', dest: 'JFK' },
  'AAL507': { origin: 'CLT', dest: 'JFK' },
  'AAL509': { origin: 'CLT', dest: 'DFW' },
  'AAL511': { origin: 'CLT', dest: 'DFW' },
  'AAL513': { origin: 'CLT', dest: 'ORD' },
  'AAL515': { origin: 'CLT', dest: 'MIA' },
  'AAL517': { origin: 'CLT', dest: 'MIA' },
  'AAL519': { origin: 'CLT', dest: 'BOS' },
  'AAL521': { origin: 'CLT', dest: 'BOS' },
  'AAL523': { origin: 'CLT', dest: 'ATL' },
  'AAL525': { origin: 'CLT', dest: 'DEN' },
  'AAL527': { origin: 'CLT', dest: 'PHX' },
  'AAL529': { origin: 'CLT', dest: 'SEA' },
  'AAL531': { origin: 'CLT', dest: 'EWR' },
  'AAL533': { origin: 'CLT', dest: 'EWR' },
  'AAL535': { origin: 'CLT', dest: 'LAS' },
  'AAL537': { origin: 'CLT', dest: 'MCO' },
  'AAL539': { origin: 'CLT', dest: 'MSY' },
  'AAL541': { origin: 'CLT', dest: 'BNA' },
  'AAL543': { origin: 'CLT', dest: 'DTW' },
  'AAL545': { origin: 'CLT', dest: 'MSP' },
  'AAL547': { origin: 'CLT', dest: 'IAH' },

  // American MIA hub
  'AAL601': { origin: 'MIA', dest: 'LAX' },
  'AAL603': { origin: 'MIA', dest: 'LAX' },
  'AAL605': { origin: 'MIA', dest: 'JFK' },
  'AAL607': { origin: 'MIA', dest: 'JFK' },
  'AAL609': { origin: 'MIA', dest: 'DFW' },
  'AAL611': { origin: 'MIA', dest: 'DFW' },
  'AAL613': { origin: 'MIA', dest: 'ORD' },
  'AAL615': { origin: 'MIA', dest: 'ORD' },
  'AAL617': { origin: 'MIA', dest: 'CLT' },
  'AAL619': { origin: 'MIA', dest: 'CLT' },
  'AAL621': { origin: 'MIA', dest: 'BOS' },
  'AAL623': { origin: 'MIA', dest: 'EWR' },
  'AAL625': { origin: 'MIA', dest: 'ATL' },
  'AAL627': { origin: 'MIA', dest: 'DEN' },
  'AAL629': { origin: 'MIA', dest: 'PHX' },
  'AAL631': { origin: 'MIA', dest: 'SFO' },

  // American PHX hub
  'AAL651': { origin: 'PHX', dest: 'DFW' },
  'AAL653': { origin: 'PHX', dest: 'DFW' },
  'AAL655': { origin: 'PHX', dest: 'LAX' },
  'AAL657': { origin: 'PHX', dest: 'LAX' },
  'AAL659': { origin: 'PHX', dest: 'ORD' },
  'AAL661': { origin: 'PHX', dest: 'CLT' },
  'AAL663': { origin: 'PHX', dest: 'MIA' },
  'AAL665': { origin: 'PHX', dest: 'JFK' },
  'AAL667': { origin: 'PHX', dest: 'SFO' },
  'AAL669': { origin: 'PHX', dest: 'SEA' },
  'AAL671': { origin: 'PHX', dest: 'DEN' },
  'AAL673': { origin: 'PHX', dest: 'ATL' },
  'AAL675': { origin: 'PHX', dest: 'LAS' },
  'AAL677': { origin: 'PHX', dest: 'EWR' },
  'AAL679': { origin: 'PHX', dest: 'BOS' },
  'AAL681': { origin: 'PHX', dest: 'MSP' },
  'AAL683': { origin: 'PHX', dest: 'ABQ' },
  'AAL685': { origin: 'PHX', dest: 'TUS' },
  'AAL687': { origin: 'PHX', dest: 'ELP' },
  'AAL689': { origin: 'PHX', dest: 'SAN' },

  // American ORD hub
  'AAL701': { origin: 'ORD', dest: 'LAX' },
  'AAL703': { origin: 'ORD', dest: 'LAX' },
  'AAL705': { origin: 'ORD', dest: 'SFO' },
  'AAL707': { origin: 'ORD', dest: 'DFW' },
  'AAL709': { origin: 'ORD', dest: 'DFW' },
  'AAL711': { origin: 'ORD', dest: 'MIA' },
  'AAL713': { origin: 'ORD', dest: 'JFK' },
  'AAL715': { origin: 'ORD', dest: 'JFK' },
  'AAL717': { origin: 'ORD', dest: 'CLT' },
  'AAL719': { origin: 'ORD', dest: 'PHX' },
  'AAL721': { origin: 'ORD', dest: 'BOS' },
  'AAL723': { origin: 'ORD', dest: 'SEA' },
  'AAL725': { origin: 'ORD', dest: 'DEN' },
  'AAL727': { origin: 'ORD', dest: 'LAS' },
  'AAL729': { origin: 'ORD', dest: 'MCO' },
  'AAL731': { origin: 'ORD', dest: 'EWR' },

  // American JFK
  'AAL21': { origin: 'JFK', dest: 'LAX' },
  'AAL23': { origin: 'JFK', dest: 'SFO' },
  'AAL25': { origin: 'JFK', dest: 'MIA' },
  'AAL27': { origin: 'JFK', dest: 'DFW' },
  'AAL29': { origin: 'JFK', dest: 'ORD' },

  // American LAX
  'AAL31': { origin: 'LAX', dest: 'JFK' },
  'AAL33': { origin: 'LAX', dest: 'DFW' },
  'AAL35': { origin: 'LAX', dest: 'ORD' },
  'AAL37': { origin: 'LAX', dest: 'MIA' },
  'AAL39': { origin: 'LAX', dest: 'PHX' },
  'AAL41': { origin: 'LAX', dest: 'CLT' },
  'AAL43': { origin: 'LAX', dest: 'SFO' },

  // ============================================================
  // UNITED AIRLINES (UAL)
  // Major hubs: ORD, EWR, IAH, DEN, SFO, LAX
  // ============================================================

  // United flagship / low-number routes
  'UAL1': { origin: 'SFO', dest: 'EWR' },
  'UAL2': { origin: 'EWR', dest: 'SFO' },
  'UAL3': { origin: 'SFO', dest: 'EWR' },
  'UAL4': { origin: 'EWR', dest: 'SFO' },
  'UAL5': { origin: 'LAX', dest: 'EWR' },
  'UAL6': { origin: 'EWR', dest: 'LAX' },

  // United ORD hub
  'UAL201': { origin: 'ORD', dest: 'LAX' },
  'UAL203': { origin: 'ORD', dest: 'LAX' },
  'UAL205': { origin: 'ORD', dest: 'LAX' },
  'UAL211': { origin: 'ORD', dest: 'SFO' },
  'UAL213': { origin: 'ORD', dest: 'SFO' },
  'UAL215': { origin: 'ORD', dest: 'SFO' },
  'UAL221': { origin: 'ORD', dest: 'EWR' },
  'UAL223': { origin: 'ORD', dest: 'EWR' },
  'UAL231': { origin: 'ORD', dest: 'DEN' },
  'UAL233': { origin: 'ORD', dest: 'DEN' },
  'UAL235': { origin: 'ORD', dest: 'DEN' },
  'UAL241': { origin: 'ORD', dest: 'IAH' },
  'UAL243': { origin: 'ORD', dest: 'IAH' },
  'UAL245': { origin: 'ORD', dest: 'IAH' },
  'UAL251': { origin: 'ORD', dest: 'SEA' },
  'UAL253': { origin: 'ORD', dest: 'SEA' },
  'UAL261': { origin: 'ORD', dest: 'MIA' },
  'UAL263': { origin: 'ORD', dest: 'MIA' },
  'UAL271': { origin: 'ORD', dest: 'BOS' },
  'UAL273': { origin: 'ORD', dest: 'BOS' },
  'UAL275': { origin: 'ORD', dest: 'ATL' },
  'UAL277': { origin: 'ORD', dest: 'DFW' },
  'UAL279': { origin: 'ORD', dest: 'PHX' },
  'UAL281': { origin: 'ORD', dest: 'LAS' },
  'UAL283': { origin: 'ORD', dest: 'LAS' },
  'UAL285': { origin: 'ORD', dest: 'MCO' },
  'UAL287': { origin: 'ORD', dest: 'MSP' },
  'UAL289': { origin: 'ORD', dest: 'MSY' },
  'UAL291': { origin: 'ORD', dest: 'AUS' },
  'UAL293': { origin: 'ORD', dest: 'BNA' },
  'UAL295': { origin: 'ORD', dest: 'SAN' },
  'UAL297': { origin: 'ORD', dest: 'CLT' },

  // United EWR hub
  'UAL301': { origin: 'EWR', dest: 'LAX' },
  'UAL303': { origin: 'EWR', dest: 'LAX' },
  'UAL305': { origin: 'EWR', dest: 'SFO' },
  'UAL307': { origin: 'EWR', dest: 'SFO' },
  'UAL311': { origin: 'EWR', dest: 'ORD' },
  'UAL313': { origin: 'EWR', dest: 'ORD' },
  'UAL315': { origin: 'EWR', dest: 'DEN' },
  'UAL317': { origin: 'EWR', dest: 'DEN' },
  'UAL321': { origin: 'EWR', dest: 'IAH' },
  'UAL323': { origin: 'EWR', dest: 'IAH' },
  'UAL325': { origin: 'EWR', dest: 'MIA' },
  'UAL327': { origin: 'EWR', dest: 'MIA' },
  'UAL331': { origin: 'EWR', dest: 'ATL' },
  'UAL333': { origin: 'EWR', dest: 'SEA' },
  'UAL335': { origin: 'EWR', dest: 'BOS' },
  'UAL337': { origin: 'EWR', dest: 'DFW' },
  'UAL339': { origin: 'EWR', dest: 'PHX' },
  'UAL341': { origin: 'EWR', dest: 'LAS' },
  'UAL343': { origin: 'EWR', dest: 'MCO' },
  'UAL345': { origin: 'EWR', dest: 'MCO' },
  'UAL347': { origin: 'EWR', dest: 'MSY' },
  'UAL349': { origin: 'EWR', dest: 'AUS' },
  'UAL351': { origin: 'EWR', dest: 'BNA' },
  'UAL353': { origin: 'EWR', dest: 'CLT' },
  'UAL355': { origin: 'EWR', dest: 'MSP' },
  'UAL357': { origin: 'EWR', dest: 'DTW' },
  'UAL359': { origin: 'EWR', dest: 'SAN' },

  // United IAH hub
  'UAL401': { origin: 'IAH', dest: 'LAX' },
  'UAL403': { origin: 'IAH', dest: 'LAX' },
  'UAL405': { origin: 'IAH', dest: 'SFO' },
  'UAL407': { origin: 'IAH', dest: 'SFO' },
  'UAL411': { origin: 'IAH', dest: 'ORD' },
  'UAL413': { origin: 'IAH', dest: 'ORD' },
  'UAL415': { origin: 'IAH', dest: 'EWR' },
  'UAL417': { origin: 'IAH', dest: 'EWR' },
  'UAL421': { origin: 'IAH', dest: 'DEN' },
  'UAL423': { origin: 'IAH', dest: 'DEN' },
  'UAL425': { origin: 'IAH', dest: 'DFW' },
  'UAL427': { origin: 'IAH', dest: 'MIA' },
  'UAL429': { origin: 'IAH', dest: 'ATL' },
  'UAL431': { origin: 'IAH', dest: 'SEA' },
  'UAL433': { origin: 'IAH', dest: 'BOS' },
  'UAL435': { origin: 'IAH', dest: 'PHX' },
  'UAL437': { origin: 'IAH', dest: 'LAS' },
  'UAL439': { origin: 'IAH', dest: 'MCO' },
  'UAL441': { origin: 'IAH', dest: 'MSY' },
  'UAL443': { origin: 'IAH', dest: 'AUS' },
  'UAL445': { origin: 'IAH', dest: 'BNA' },
  'UAL447': { origin: 'IAH', dest: 'MSP' },
  'UAL449': { origin: 'IAH', dest: 'CLT' },
  'UAL451': { origin: 'IAH', dest: 'SAN' },
  'UAL453': { origin: 'IAH', dest: 'ELP' },
  'UAL455': { origin: 'IAH', dest: 'ABQ' },

  // United DEN hub
  'UAL501': { origin: 'DEN', dest: 'LAX' },
  'UAL503': { origin: 'DEN', dest: 'LAX' },
  'UAL505': { origin: 'DEN', dest: 'SFO' },
  'UAL507': { origin: 'DEN', dest: 'SFO' },
  'UAL511': { origin: 'DEN', dest: 'ORD' },
  'UAL513': { origin: 'DEN', dest: 'ORD' },
  'UAL515': { origin: 'DEN', dest: 'EWR' },
  'UAL517': { origin: 'DEN', dest: 'EWR' },
  'UAL521': { origin: 'DEN', dest: 'IAH' },
  'UAL523': { origin: 'DEN', dest: 'IAH' },
  'UAL525': { origin: 'DEN', dest: 'SEA' },
  'UAL527': { origin: 'DEN', dest: 'SEA' },
  'UAL531': { origin: 'DEN', dest: 'ATL' },
  'UAL533': { origin: 'DEN', dest: 'DFW' },
  'UAL535': { origin: 'DEN', dest: 'BOS' },
  'UAL537': { origin: 'DEN', dest: 'PHX' },
  'UAL539': { origin: 'DEN', dest: 'LAS' },
  'UAL541': { origin: 'DEN', dest: 'MCO' },
  'UAL543': { origin: 'DEN', dest: 'MIA' },
  'UAL545': { origin: 'DEN', dest: 'MSP' },
  'UAL547': { origin: 'DEN', dest: 'JFK' },
  'UAL549': { origin: 'DEN', dest: 'AUS' },
  'UAL551': { origin: 'DEN', dest: 'BNA' },
  'UAL553': { origin: 'DEN', dest: 'MSY' },
  'UAL555': { origin: 'DEN', dest: 'SAN' },
  'UAL557': { origin: 'DEN', dest: 'ABQ' },
  'UAL559': { origin: 'DEN', dest: 'ELP' },
  'UAL561': { origin: 'DEN', dest: 'TUS' },

  // United SFO hub
  'UAL601': { origin: 'SFO', dest: 'LAX' },
  'UAL603': { origin: 'SFO', dest: 'LAX' },
  'UAL611': { origin: 'SFO', dest: 'ORD' },
  'UAL613': { origin: 'SFO', dest: 'ORD' },
  'UAL615': { origin: 'SFO', dest: 'EWR' },
  'UAL617': { origin: 'SFO', dest: 'EWR' },
  'UAL621': { origin: 'SFO', dest: 'DEN' },
  'UAL623': { origin: 'SFO', dest: 'DEN' },
  'UAL625': { origin: 'SFO', dest: 'IAH' },
  'UAL627': { origin: 'SFO', dest: 'SEA' },
  'UAL629': { origin: 'SFO', dest: 'BOS' },
  'UAL631': { origin: 'SFO', dest: 'ATL' },
  'UAL633': { origin: 'SFO', dest: 'DFW' },
  'UAL635': { origin: 'SFO', dest: 'JFK' },
  'UAL637': { origin: 'SFO', dest: 'PHX' },
  'UAL639': { origin: 'SFO', dest: 'SAN' },

  // ============================================================
  // SOUTHWEST AIRLINES (SWA)
  // Major bases: DAL, MDW, BWI, LAS, DEN, PHX
  // Note: Southwest uses Love Field (DAL) in Dallas
  // ============================================================

  // Southwest MDW (Chicago Midway) routes
  'SWA101': { origin: 'MDW', dest: 'LAS' },
  'SWA103': { origin: 'MDW', dest: 'LAS' },
  'SWA105': { origin: 'MDW', dest: 'DEN' },
  'SWA107': { origin: 'MDW', dest: 'DEN' },
  'SWA109': { origin: 'MDW', dest: 'PHX' },
  'SWA111': { origin: 'MDW', dest: 'PHX' },
  'SWA113': { origin: 'MDW', dest: 'LAX' },
  'SWA115': { origin: 'MDW', dest: 'LAX' },
  'SWA117': { origin: 'MDW', dest: 'ATL' },
  'SWA119': { origin: 'MDW', dest: 'ATL' },
  'SWA121': { origin: 'MDW', dest: 'MCO' },
  'SWA123': { origin: 'MDW', dest: 'MCO' },
  'SWA125': { origin: 'MDW', dest: 'BNA' },
  'SWA127': { origin: 'MDW', dest: 'BNA' },
  'SWA129': { origin: 'MDW', dest: 'MSY' },
  'SWA131': { origin: 'MDW', dest: 'MIA' },
  'SWA133': { origin: 'MDW', dest: 'DFW' },
  'SWA135': { origin: 'MDW', dest: 'AUS' },
  'SWA137': { origin: 'MDW', dest: 'BWI' },
  'SWA139': { origin: 'MDW', dest: 'BOS' },
  'SWA141': { origin: 'MDW', dest: 'MSP' },
  'SWA143': { origin: 'MDW', dest: 'SAN' },
  'SWA145': { origin: 'MDW', dest: 'IAH' },
  'SWA147': { origin: 'MDW', dest: 'SEA' },
  'SWA149': { origin: 'MDW', dest: 'SFO' },

  // Southwest LAS (Las Vegas) routes
  'SWA201': { origin: 'LAS', dest: 'LAX' },
  'SWA203': { origin: 'LAS', dest: 'LAX' },
  'SWA205': { origin: 'LAS', dest: 'DEN' },
  'SWA207': { origin: 'LAS', dest: 'DEN' },
  'SWA209': { origin: 'LAS', dest: 'PHX' },
  'SWA211': { origin: 'LAS', dest: 'PHX' },
  'SWA213': { origin: 'LAS', dest: 'SFO' },
  'SWA215': { origin: 'LAS', dest: 'SFO' },
  'SWA217': { origin: 'LAS', dest: 'SEA' },
  'SWA219': { origin: 'LAS', dest: 'SEA' },
  'SWA221': { origin: 'LAS', dest: 'MDW' },
  'SWA223': { origin: 'LAS', dest: 'MDW' },
  'SWA225': { origin: 'LAS', dest: 'ATL' },
  'SWA227': { origin: 'LAS', dest: 'MCO' },
  'SWA229': { origin: 'LAS', dest: 'DFW' },
  'SWA231': { origin: 'LAS', dest: 'BWI' },
  'SWA233': { origin: 'LAS', dest: 'AUS' },
  'SWA235': { origin: 'LAS', dest: 'BNA' },
  'SWA237': { origin: 'LAS', dest: 'MSP' },
  'SWA239': { origin: 'LAS', dest: 'SAN' },
  'SWA241': { origin: 'LAS', dest: 'ABQ' },
  'SWA243': { origin: 'LAS', dest: 'ELP' },

  // Southwest DEN (Denver) routes
  'SWA301': { origin: 'DEN', dest: 'LAS' },
  'SWA303': { origin: 'DEN', dest: 'LAS' },
  'SWA305': { origin: 'DEN', dest: 'PHX' },
  'SWA307': { origin: 'DEN', dest: 'PHX' },
  'SWA309': { origin: 'DEN', dest: 'LAX' },
  'SWA311': { origin: 'DEN', dest: 'LAX' },
  'SWA313': { origin: 'DEN', dest: 'MDW' },
  'SWA315': { origin: 'DEN', dest: 'SFO' },
  'SWA317': { origin: 'DEN', dest: 'SEA' },
  'SWA319': { origin: 'DEN', dest: 'ATL' },
  'SWA321': { origin: 'DEN', dest: 'MCO' },
  'SWA323': { origin: 'DEN', dest: 'DFW' },
  'SWA325': { origin: 'DEN', dest: 'AUS' },
  'SWA327': { origin: 'DEN', dest: 'BNA' },
  'SWA329': { origin: 'DEN', dest: 'MSY' },
  'SWA331': { origin: 'DEN', dest: 'BWI' },
  'SWA333': { origin: 'DEN', dest: 'MSP' },
  'SWA335': { origin: 'DEN', dest: 'SAN' },
  'SWA337': { origin: 'DEN', dest: 'ABQ' },
  'SWA339': { origin: 'DEN', dest: 'ELP' },
  'SWA341': { origin: 'DEN', dest: 'TUS' },
  'SWA343': { origin: 'DEN', dest: 'BOS' },

  // Southwest PHX routes
  'SWA401': { origin: 'PHX', dest: 'LAS' },
  'SWA403': { origin: 'PHX', dest: 'DEN' },
  'SWA405': { origin: 'PHX', dest: 'LAX' },
  'SWA407': { origin: 'PHX', dest: 'MDW' },
  'SWA409': { origin: 'PHX', dest: 'SFO' },
  'SWA411': { origin: 'PHX', dest: 'SEA' },
  'SWA413': { origin: 'PHX', dest: 'ATL' },
  'SWA415': { origin: 'PHX', dest: 'DFW' },
  'SWA417': { origin: 'PHX', dest: 'MCO' },
  'SWA419': { origin: 'PHX', dest: 'AUS' },
  'SWA421': { origin: 'PHX', dest: 'SAN' },
  'SWA423': { origin: 'PHX', dest: 'ABQ' },
  'SWA425': { origin: 'PHX', dest: 'ELP' },
  'SWA427': { origin: 'PHX', dest: 'TUS' },
  'SWA429': { origin: 'PHX', dest: 'BWI' },

  // Southwest BWI (Baltimore) routes
  'SWA501': { origin: 'BWI', dest: 'ATL' },
  'SWA503': { origin: 'BWI', dest: 'MCO' },
  'SWA505': { origin: 'BWI', dest: 'MCO' },
  'SWA507': { origin: 'BWI', dest: 'LAS' },
  'SWA509': { origin: 'BWI', dest: 'DEN' },
  'SWA511': { origin: 'BWI', dest: 'MDW' },
  'SWA513': { origin: 'BWI', dest: 'BOS' },
  'SWA515': { origin: 'BWI', dest: 'PHX' },
  'SWA517': { origin: 'BWI', dest: 'LAX' },
  'SWA519': { origin: 'BWI', dest: 'DFW' },
  'SWA521': { origin: 'BWI', dest: 'MSY' },
  'SWA523': { origin: 'BWI', dest: 'BNA' },
  'SWA525': { origin: 'BWI', dest: 'AUS' },
  'SWA527': { origin: 'BWI', dest: 'MIA' },

  // Southwest DAL (Dallas Love Field) routes
  'SWA601': { origin: 'DAL', dest: 'IAH' },
  'SWA603': { origin: 'DAL', dest: 'AUS' },
  'SWA605': { origin: 'DAL', dest: 'MSY' },
  'SWA607': { origin: 'DAL', dest: 'ATL' },
  'SWA609': { origin: 'DAL', dest: 'DEN' },
  'SWA611': { origin: 'DAL', dest: 'LAS' },
  'SWA613': { origin: 'DAL', dest: 'LAX' },
  'SWA615': { origin: 'DAL', dest: 'MDW' },
  'SWA617': { origin: 'DAL', dest: 'BNA' },
  'SWA619': { origin: 'DAL', dest: 'BWI' },
  'SWA621': { origin: 'DAL', dest: 'MCO' },
  'SWA623': { origin: 'DAL', dest: 'PHX' },
  'SWA625': { origin: 'DAL', dest: 'ELP' },

  // ============================================================
  // JETBLUE AIRWAYS (JBU)
  // Major bases: JFK, BOS, FLL (Fort Lauderdale = MIA area), MCO
  // Note: FLL not in allowed list, using MIA for South Florida
  // ============================================================

  // JetBlue JFK routes
  'JBU501': { origin: 'JFK', dest: 'LAX' },
  'JBU503': { origin: 'JFK', dest: 'LAX' },
  'JBU505': { origin: 'JFK', dest: 'SFO' },
  'JBU507': { origin: 'JFK', dest: 'SFO' },
  'JBU509': { origin: 'JFK', dest: 'BOS' },
  'JBU511': { origin: 'JFK', dest: 'BOS' },
  'JBU513': { origin: 'JFK', dest: 'MCO' },
  'JBU515': { origin: 'JFK', dest: 'MCO' },
  'JBU517': { origin: 'JFK', dest: 'MCO' },
  'JBU519': { origin: 'JFK', dest: 'MIA' },
  'JBU521': { origin: 'JFK', dest: 'MIA' },
  'JBU523': { origin: 'JFK', dest: 'ATL' },
  'JBU525': { origin: 'JFK', dest: 'SEA' },
  'JBU527': { origin: 'JFK', dest: 'LAS' },
  'JBU529': { origin: 'JFK', dest: 'DEN' },
  'JBU531': { origin: 'JFK', dest: 'AUS' },
  'JBU533': { origin: 'JFK', dest: 'MSY' },
  'JBU535': { origin: 'JFK', dest: 'SAN' },
  'JBU537': { origin: 'JFK', dest: 'PHX' },
  'JBU539': { origin: 'JFK', dest: 'BNA' },
  'JBU541': { origin: 'JFK', dest: 'DFW' },
  'JBU543': { origin: 'JFK', dest: 'CLT' },

  // JetBlue BOS routes
  'JBU601': { origin: 'BOS', dest: 'JFK' },
  'JBU603': { origin: 'BOS', dest: 'LAX' },
  'JBU605': { origin: 'BOS', dest: 'SFO' },
  'JBU607': { origin: 'BOS', dest: 'MCO' },
  'JBU609': { origin: 'BOS', dest: 'MCO' },
  'JBU611': { origin: 'BOS', dest: 'MIA' },
  'JBU613': { origin: 'BOS', dest: 'ATL' },
  'JBU615': { origin: 'BOS', dest: 'SEA' },
  'JBU617': { origin: 'BOS', dest: 'LAS' },
  'JBU619': { origin: 'BOS', dest: 'DEN' },
  'JBU621': { origin: 'BOS', dest: 'AUS' },
  'JBU623': { origin: 'BOS', dest: 'MSY' },
  'JBU625': { origin: 'BOS', dest: 'SAN' },
  'JBU627': { origin: 'BOS', dest: 'DFW' },
  'JBU629': { origin: 'BOS', dest: 'PHX' },
  'JBU631': { origin: 'BOS', dest: 'BNA' },
  'JBU633': { origin: 'BOS', dest: 'EWR' },

  // JetBlue MCO routes
  'JBU701': { origin: 'MCO', dest: 'JFK' },
  'JBU703': { origin: 'MCO', dest: 'JFK' },
  'JBU705': { origin: 'MCO', dest: 'BOS' },
  'JBU707': { origin: 'MCO', dest: 'BOS' },
  'JBU709': { origin: 'MCO', dest: 'EWR' },
  'JBU711': { origin: 'MCO', dest: 'LAX' },
  'JBU713': { origin: 'MCO', dest: 'DEN' },

  // JetBlue MIA / South Florida routes
  'JBU801': { origin: 'MIA', dest: 'JFK' },
  'JBU803': { origin: 'MIA', dest: 'BOS' },
  'JBU805': { origin: 'MIA', dest: 'LAX' },
  'JBU807': { origin: 'MIA', dest: 'EWR' },
  'JBU809': { origin: 'MIA', dest: 'ATL' },
  'JBU811': { origin: 'MIA', dest: 'DEN' },

  // ============================================================
  // ALASKA AIRLINES (ASA)
  // Major hubs: SEA, PDX (not in list), SFO, LAX
  // ============================================================

  // Alaska SEA hub routes
  'ASA101': { origin: 'SEA', dest: 'LAX' },
  'ASA103': { origin: 'SEA', dest: 'LAX' },
  'ASA105': { origin: 'SEA', dest: 'LAX' },
  'ASA111': { origin: 'SEA', dest: 'SFO' },
  'ASA113': { origin: 'SEA', dest: 'SFO' },
  'ASA115': { origin: 'SEA', dest: 'SFO' },
  'ASA121': { origin: 'SEA', dest: 'SAN' },
  'ASA123': { origin: 'SEA', dest: 'SAN' },
  'ASA131': { origin: 'SEA', dest: 'PHX' },
  'ASA133': { origin: 'SEA', dest: 'PHX' },
  'ASA141': { origin: 'SEA', dest: 'LAS' },
  'ASA143': { origin: 'SEA', dest: 'LAS' },
  'ASA151': { origin: 'SEA', dest: 'DEN' },
  'ASA153': { origin: 'SEA', dest: 'DEN' },
  'ASA161': { origin: 'SEA', dest: 'DFW' },
  'ASA163': { origin: 'SEA', dest: 'DFW' },
  'ASA171': { origin: 'SEA', dest: 'ORD' },
  'ASA173': { origin: 'SEA', dest: 'ORD' },
  'ASA175': { origin: 'SEA', dest: 'JFK' },
  'ASA177': { origin: 'SEA', dest: 'EWR' },
  'ASA179': { origin: 'SEA', dest: 'BOS' },
  'ASA181': { origin: 'SEA', dest: 'ATL' },
  'ASA183': { origin: 'SEA', dest: 'MSP' },
  'ASA185': { origin: 'SEA', dest: 'IAH' },
  'ASA187': { origin: 'SEA', dest: 'MCO' },
  'ASA189': { origin: 'SEA', dest: 'AUS' },
  'ASA191': { origin: 'SEA', dest: 'BNA' },
  'ASA193': { origin: 'SEA', dest: 'MSY' },
  'ASA195': { origin: 'SEA', dest: 'ABQ' },

  // Alaska SFO routes
  'ASA201': { origin: 'SFO', dest: 'SEA' },
  'ASA203': { origin: 'SFO', dest: 'SEA' },
  'ASA205': { origin: 'SFO', dest: 'LAX' },
  'ASA207': { origin: 'SFO', dest: 'SAN' },
  'ASA209': { origin: 'SFO', dest: 'PHX' },
  'ASA211': { origin: 'SFO', dest: 'LAS' },
  'ASA213': { origin: 'SFO', dest: 'DEN' },
  'ASA215': { origin: 'SFO', dest: 'ORD' },
  'ASA217': { origin: 'SFO', dest: 'EWR' },
  'ASA219': { origin: 'SFO', dest: 'JFK' },
  'ASA221': { origin: 'SFO', dest: 'BOS' },
  'ASA223': { origin: 'SFO', dest: 'DFW' },
  'ASA225': { origin: 'SFO', dest: 'ATL' },
  'ASA227': { origin: 'SFO', dest: 'IAH' },
  'ASA229': { origin: 'SFO', dest: 'AUS' },

  // Alaska LAX routes
  'ASA301': { origin: 'LAX', dest: 'SEA' },
  'ASA303': { origin: 'LAX', dest: 'SEA' },
  'ASA305': { origin: 'LAX', dest: 'SFO' },
  'ASA307': { origin: 'LAX', dest: 'SAN' },
  'ASA309': { origin: 'LAX', dest: 'PHX' },
  'ASA311': { origin: 'LAX', dest: 'LAS' },
  'ASA313': { origin: 'LAX', dest: 'DEN' },
  'ASA315': { origin: 'LAX', dest: 'ORD' },
  'ASA317': { origin: 'LAX', dest: 'JFK' },
  'ASA319': { origin: 'LAX', dest: 'EWR' },
  'ASA321': { origin: 'LAX', dest: 'BOS' },
  'ASA323': { origin: 'LAX', dest: 'DFW' },
  'ASA325': { origin: 'LAX', dest: 'ATL' },
  'ASA327': { origin: 'LAX', dest: 'MSP' },
  'ASA329': { origin: 'LAX', dest: 'ABQ' },
  'ASA331': { origin: 'LAX', dest: 'AUS' },
};

export default routesDB;
